services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: P14MySQL
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: splunge
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-db:
      
